### ISSUE TITLE
SELECT queries on temporal tables

### ISSUE THREAD

**Issue by anandsowm** [mlt/temporal_tables#1]
I have installed temporal_tables extension for my Postgresql 13 64bit running on Win10. I have created temporal and history table and able to see it in action. How do I query using SELECT such that I can retrieve current values and all historical values of my entity? The sql server follows the syntax, SELECT * from base_table FOR SYSTEM_TIME ALL , what is the equivalent syntax with this extension ? Thanks in advance.

Edit 1: 
  SELECT * FROM items where sys_period @> '2021-06-20 1:00:00.12+05:30'::timestamptz;  is returning results just fine.

**Comment by anandsowm** [comment]
@mlt, I understand you would like us to redirect to using the "periods" extension. 
Edit: I was able to compile the period extension from your repo and was able to create table with system_versioning , thanks much. I am not able to differentiate the ```__between``` and ```__from_to``` functions, more details will help.

**Comment by mlt** [comment]
Periods tries to follow the standard more closely compared to temporal_tables. The home page for *periods* is https://github.com/xocolatl/periods . Don't use my repo as it is outdated and I'm not the author. You can follow AppVeyor build to see how to compile it https://ci.appveyor.com/project/xocolatl/periods . You can use [msbuild](https://github.com/xocolatl/periods/blob/master/appveyor.yml#L80) or adjust env variables to match your set up and run Visual Studio as usual. If you have general questions or comments on periods (not serious issues or something Windows specific) you can find the author and get your answers quicker on ~~freenode~~ libera IRC #postgresql channel.
